// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-JegLT9e43DMfRYOs4Qqn8to2u1bYlbo',
    appId: '1:212612973375:web:48d3d72e5196b7fadb498a',
    messagingSenderId: '212612973375',
    projectId: 'hoops-connect-jm',
    authDomain: 'hoops-connect-jm.firebaseapp.com',
    storageBucket: 'hoops-connect-jm.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB02xmieJ4k26duJNwDL0lnBCm6WpZ29TM',
    appId: '1:212612973375:android:2b6139ac0f5ee182db498a',
    messagingSenderId: '212612973375',
    projectId: 'hoops-connect-jm',
    storageBucket: 'hoops-connect-jm.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTIYnyo6unze30UHyb6aEXMjq2bM0vKtQ',
    appId: '1:212612973375:ios:23ec778ad8cafa58db498a',
    messagingSenderId: '212612973375',
    projectId: 'hoops-connect-jm',
    storageBucket: 'hoops-connect-jm.firebasestorage.app',
    iosBundleId: 'com.hoopsconnect.hoopsConnect',
    iosClientId:
        '212612973375-dvk80s9vkd0cbqmoogtlv350c1htr7sc.apps.googleusercontent.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTIYnyo6unze30UHyb6aEXMjq2bM0vKtQ',
    appId: '1:212612973375:ios:23ec778ad8cafa58db498a',
    messagingSenderId: '212612973375',
    projectId: 'hoops-connect-jm',
    storageBucket: 'hoops-connect-jm.firebasestorage.app',
    iosBundleId: 'com.hoopsconnect.hoopsConnect',
    iosClientId:
        '212612973375-dvk80s9vkd0cbqmoogtlv350c1htr7sc.apps.googleusercontent.com',
  );
}
