#!/usr/bin/env node

/*
 * Produces a compressed Dart mirror of the normative shared JSON fixture.
 * VM tests prove byte-for-byte identity with the source JSON; Chrome uses the
 * generated mirror because flutter_test's browser server does not expose
 * arbitrary workspace files.
 */
const crypto = require("node:crypto");
const fs = require("node:fs");
const path = require("node:path");
const zlib = require("node:zlib");

const sourcePath = path.join(
  __dirname,
  "../contracts/official_stats/v2/box_score_calculator_fixtures.json",
);
const source = fs.readFileSync(sourcePath);
const sha256 = crypto.createHash("sha256").update(source).digest("hex");
const compressed = zlib.gzipSync(source, {level: 9, mtime: 0}).toString("base64");
const chunks = compressed.match(/.{1,100}/g) ?? [];

process.stdout.write(`// Generated by scripts/generate_box_score_browser_fixture.js.\n`);
process.stdout.write(`// The normative source is contracts/official_stats/v2/box_score_calculator_fixtures.json.\n`);
process.stdout.write(`import 'dart:convert';\n\n`);
process.stdout.write(`import 'package:archive/archive.dart';\n\n`);
process.stdout.write(`const boxScoreCalculatorFixtureSourceSha256 =\n`);
process.stdout.write(`    '${sha256}';\n`);
process.stdout.write(`const _boxScoreCalculatorFixtureGzipBase64 =\n`);
for (const [index, chunk] of chunks.entries()) {
  process.stdout.write(`    '${chunk}'${index === chunks.length - 1 ? ";" : ""}\n`);
}
process.stdout.write(`\n`);
process.stdout.write(`String loadBoxScoreCalculatorBrowserFixture() => utf8.decode(\n`);
process.stdout.write(`  GZipDecoder().decodeBytes(base64Decode(_boxScoreCalculatorFixtureGzipBase64)),\n`);
process.stdout.write(`);\n`);
