enum ContractClassification {
  canonical,
  derived,
  operational,
  publicProjection,
}

enum ContractMutability { mutableHead, immutable, appendOnly, buildThenSeal }

enum ContractVisibility { internal, private, serverPrivate, publicHttpOnly }

class EntitySchemaContract {
  final String name;
  final String path;
  final ContractClassification classification;
  final ContractMutability mutability;
  final ContractVisibility visibility;
  final Set<String> requiredFields;
  final Set<String> explicitFactFields;

  const EntitySchemaContract({
    required this.name,
    required this.path,
    required this.classification,
    required this.mutability,
    required this.visibility,
    required this.requiredFields,
    this.explicitFactFields = const {},
  });
}

/// Executable schema inventory. All scoped v2 records also require
/// `dataSchemaVersion=2`, and their duplicate scope fields must match the path.
abstract final class OfficialStatSchemaRegistry {
  static const Set<String> scopeFields = {
    'associationId',
    'competitionId',
    'seasonId',
  };

  static const List<EntitySchemaContract> entities = [
    EntitySchemaContract(
      name: 'competition',
      path: 'associations/{associationId}/competitions/{competitionId}',
      classification: ContractClassification.canonical,
      mutability: ContractMutability.mutableHead,
      visibility: ContractVisibility.internal,
      requiredFields: {
        'dataSchemaVersion',
        'associationId',
        'competitionId',
        'name',
        'sport',
        'status',
        'defaultTimezone',
      },
    ),
    EntitySchemaContract(
      name: 'season',
      path:
          'associations/{associationId}/competitions/{competitionId}/seasons/{seasonId}',
      classification: ContractClassification.canonical,
      mutability: ContractMutability.mutableHead,
      visibility: ContractVisibility.internal,
      requiredFields: {
        'dataSchemaVersion',
        'associationId',
        'competitionId',
        'seasonId',
        'name',
        'status',
        'rulesetVersion',
        'policyVersion',
      },
    ),
    EntitySchemaContract(
      name: 'rulesProfile',
      path: 'associations/{associationId}/rulesProfiles/{versionId}',
      classification: ContractClassification.canonical,
      mutability: ContractMutability.immutable,
      visibility: ContractVisibility.internal,
      requiredFields: {
        'dataSchemaVersion',
        'associationId',
        'versionId',
        'sha256',
        'playingRules',
        'foulSemantics',
        'timePrecision',
        'rosterLimits',
        'outcomeRules',
        'adoptionEvidenceRefs',
      },
    ),
    EntitySchemaContract(
      name: 'policyVersion',
      path:
          'associations/{associationId}/competitions/{competitionId}/seasons/{seasonId}/policyVersions/{versionId}',
      classification: ContractClassification.canonical,
      mutability: ContractMutability.immutable,
      visibility: ContractVisibility.internal,
      requiredFields: {
        'dataSchemaVersion',
        'associationId',
        'competitionId',
        'seasonId',
        'versionId',
        'sha256',
        'standingsPolicy',
        'qualificationPolicy',
        'transferPolicy',
        'certificationPolicy',
        'publicationPolicy',
        'correctionPolicy',
        'approvalEvidenceRefs',
      },
    ),
    EntitySchemaContract(
      name: 'teamIdentity',
      path: 'associations/{associationId}/teamIdentities/{teamId}',
      classification: ContractClassification.canonical,
      mutability: ContractMutability.mutableHead,
      visibility: ContractVisibility.internal,
      requiredFields: {
        'dataSchemaVersion',
        'associationId',
        'teamId',
        'identityVersionId',
        'status',
      },
    ),
    EntitySchemaContract(
      name: 'person',
      path: 'associations/{associationId}/persons/{personId}',
      classification: ContractClassification.canonical,
      mutability: ContractMutability.mutableHead,
      visibility: ContractVisibility.private,
      requiredFields: {
        'dataSchemaVersion',
        'associationId',
        'personId',
        'identityVersionId',
        'status',
      },
    ),
    EntitySchemaContract(
      name: 'player',
      path: 'associations/{associationId}/players/{playerId}',
      classification: ContractClassification.canonical,
      mutability: ContractMutability.mutableHead,
      visibility: ContractVisibility.internal,
      requiredFields: {
        'dataSchemaVersion',
        'associationId',
        'playerId',
        'personId',
        'displayNameVersionId',
        'status',
      },
    ),
    EntitySchemaContract(
      name: 'playerAlias',
      path: 'associations/{associationId}/playerAliases/{aliasPlayerId}',
      classification: ContractClassification.canonical,
      mutability: ContractMutability.appendOnly,
      visibility: ContractVisibility.internal,
      requiredFields: {
        'dataSchemaVersion',
        'associationId',
        'aliasPlayerId',
        'canonicalPlayerId',
        'resolutionVersion',
        'reason',
        'evidenceRefs',
      },
    ),
    EntitySchemaContract(
      name: 'teamEntry',
      path:
          'associations/{associationId}/competitions/{competitionId}/seasons/{seasonId}/teamEntries/{teamEntryId}',
      classification: ContractClassification.canonical,
      mutability: ContractMutability.mutableHead,
      visibility: ContractVisibility.internal,
      requiredFields: {
        'dataSchemaVersion',
        'associationId',
        'competitionId',
        'seasonId',
        'divisionId',
        'teamEntryId',
        'teamId',
        'seasonalIdentityVersionId',
        'registrationStatus',
      },
    ),
    EntitySchemaContract(
      name: 'rosterMembership',
      path:
          'associations/{associationId}/competitions/{competitionId}/seasons/{seasonId}/rosterMemberships/{membershipId}',
      classification: ContractClassification.canonical,
      mutability: ContractMutability.mutableHead,
      visibility: ContractVisibility.internal,
      requiredFields: {
        'dataSchemaVersion',
        'associationId',
        'competitionId',
        'seasonId',
        'membershipId',
        'membershipVersionId',
        'playerId',
        'teamEntryId',
        'eligibilityStatus',
        'effectiveFrom',
        'effectiveTo',
        'recordedAt',
      },
      explicitFactFields: {'effectiveTo'},
    ),
    EntitySchemaContract(
      name: 'rosterMembershipVersion',
      path:
          'associations/{associationId}/competitions/{competitionId}/seasons/{seasonId}/rosterMemberships/{membershipId}/versions/{versionId}',
      classification: ContractClassification.canonical,
      mutability: ContractMutability.immutable,
      visibility: ContractVisibility.private,
      requiredFields: {
        'dataSchemaVersion',
        'associationId',
        'competitionId',
        'seasonId',
        'membershipId',
        'versionId',
        'completeFacts',
        'actorId',
        'reasonCode',
        'evidenceRefs',
      },
    ),
    EntitySchemaContract(
      name: 'rosterAssertion',
      path:
          'associations/{associationId}/competitions/{competitionId}/seasons/{seasonId}/rosterAssertions/{assertionId}',
      classification: ContractClassification.canonical,
      mutability: ContractMutability.appendOnly,
      visibility: ContractVisibility.internal,
      requiredFields: {
        'dataSchemaVersion',
        'associationId',
        'competitionId',
        'seasonId',
        'assertionId',
        'teamEntryId',
        'expectedRosterVersion',
        'status',
        'evidenceRefs',
      },
    ),
    EntitySchemaContract(
      name: 'game',
      path:
          'associations/{associationId}/competitions/{competitionId}/seasons/{seasonId}/games/{gameId}',
      classification: ContractClassification.canonical,
      mutability: ContractMutability.mutableHead,
      visibility: ContractVisibility.internal,
      requiredFields: {
        'dataSchemaVersion',
        'associationId',
        'competitionId',
        'seasonId',
        'divisionId',
        'phaseId',
        'gameId',
        'homeTeamEntryId',
        'awayTeamEntryId',
        'playState',
        'reviewState',
        'publicationState',
        'controlVersion',
      },
    ),
    EntitySchemaContract(
      name: 'scheduleRevision',
      path:
          'associations/{associationId}/competitions/{competitionId}/seasons/{seasonId}/games/{gameId}/scheduleRevisions/{versionId}',
      classification: ContractClassification.canonical,
      mutability: ContractMutability.immutable,
      visibility: ContractVisibility.internal,
      requiredFields: {
        'dataSchemaVersion',
        'associationId',
        'competitionId',
        'seasonId',
        'gameId',
        'versionId',
        'predecessorVersionId',
        'scheduledStart',
        'scheduledEnd',
        'timezone',
        'venueId',
        'courtId',
        'homeTeamEntryId',
        'awayTeamEntryId',
        'reasonCode',
      },
      explicitFactFields: {
        'scheduledStart',
        'scheduledEnd',
        'venueId',
        'courtId',
      },
    ),
    EntitySchemaContract(
      name: 'gameAssignment',
      path:
          'associations/{associationId}/competitions/{competitionId}/seasons/{seasonId}/games/{gameId}/assignments/{uid}',
      classification: ContractClassification.canonical,
      mutability: ContractMutability.mutableHead,
      visibility: ContractVisibility.private,
      requiredFields: {
        'dataSchemaVersion',
        'associationId',
        'competitionId',
        'seasonId',
        'gameId',
        'uid',
        'duties',
        'status',
        'assignmentVersion',
      },
    ),
    EntitySchemaContract(
      name: 'rosterSnapshot',
      path:
          'associations/{associationId}/competitions/{competitionId}/seasons/{seasonId}/games/{gameId}/rosterSnapshots/{snapshotId}',
      classification: ContractClassification.canonical,
      mutability: ContractMutability.immutable,
      visibility: ContractVisibility.internal,
      requiredFields: {
        'dataSchemaVersion',
        'associationId',
        'competitionId',
        'seasonId',
        'gameId',
        'snapshotId',
        'snapshotHash',
        'participants',
      },
    ),
    EntitySchemaContract(
      name: 'workspace',
      path:
          'associations/{associationId}/competitions/{competitionId}/seasons/{seasonId}/games/{gameId}/workspaces/{workspaceId}',
      classification: ContractClassification.operational,
      mutability: ContractMutability.mutableHead,
      visibility: ContractVisibility.private,
      requiredFields: {
        'dataSchemaVersion',
        'associationId',
        'competitionId',
        'seasonId',
        'gameId',
        'workspaceId',
        'captureMode',
        'baseRevisionId',
        'writerEpoch',
        'acceptedJournalHead',
        'acceptedJournalHash',
        'status',
      },
      explicitFactFields: {'baseRevisionId'},
    ),
    EntitySchemaContract(
      name: 'journalOperation',
      path:
          'associations/{associationId}/competitions/{competitionId}/seasons/{seasonId}/games/{gameId}/workspaces/{workspaceId}/operations/{operationId}',
      classification: ContractClassification.operational,
      mutability: ContractMutability.immutable,
      visibility: ContractVisibility.private,
      requiredFields: {
        'dataSchemaVersion',
        'associationId',
        'competitionId',
        'seasonId',
        'gameId',
        'workspaceId',
        'operationId',
        'commandId',
        'serverSequence',
        'payloadHash',
        'writerEpoch',
        'actorAccountId',
      },
    ),
    EntitySchemaContract(
      name: 'journalCheckpoint',
      path:
          'associations/{associationId}/competitions/{competitionId}/seasons/{seasonId}/games/{gameId}/workspaces/{workspaceId}/checkpoints/{checkpointId}',
      classification: ContractClassification.derived,
      mutability: ContractMutability.immutable,
      visibility: ContractVisibility.private,
      requiredFields: {
        'dataSchemaVersion',
        'associationId',
        'competitionId',
        'seasonId',
        'gameId',
        'workspaceId',
        'checkpointId',
        'coveredSequence',
        'reducerVersion',
        'checksum',
      },
    ),
    EntitySchemaContract(
      name: 'statRevision',
      path:
          'associations/{associationId}/competitions/{competitionId}/seasons/{seasonId}/games/{gameId}/statRevisions/{revisionId}',
      classification: ContractClassification.canonical,
      mutability: ContractMutability.immutable,
      visibility: ContractVisibility.private,
      requiredFields: {
        'dataSchemaVersion',
        'associationId',
        'competitionId',
        'seasonId',
        'divisionId',
        'phaseId',
        'gameId',
        'revisionId',
        'revisionNumber',
        'captureMode',
        'resultDisposition',
        'statisticsDisposition',
        'rulesetVersion',
        'policyVersion',
        'calculatorVersion',
        'scheduleRevisionId',
        'rosterSnapshotId',
        'rosterSnapshotHash',
        'sourceWorkspaceId',
        'acceptedThroughSequence',
        'journalHash',
        'inputHash',
        'derivedHash',
        'validationReportHash',
      },
      explicitFactFields: {'supersedesRevisionId', 'officialScoreEvidenceRefs'},
    ),
    EntitySchemaContract(
      name: 'statRevisionPart',
      path:
          'associations/{associationId}/competitions/{competitionId}/seasons/{seasonId}/games/{gameId}/statRevisions/{revisionId}/parts/{partId}',
      classification: ContractClassification.canonical,
      mutability: ContractMutability.immutable,
      visibility: ContractVisibility.private,
      requiredFields: {
        'dataSchemaVersion',
        'associationId',
        'competitionId',
        'seasonId',
        'gameId',
        'revisionId',
        'partId',
        'kind',
        'count',
        'sha256',
        'payload',
      },
    ),
    EntitySchemaContract(
      name: 'review',
      path:
          'associations/{associationId}/competitions/{competitionId}/seasons/{seasonId}/games/{gameId}/reviews/{reviewId}',
      classification: ContractClassification.canonical,
      mutability: ContractMutability.immutable,
      visibility: ContractVisibility.private,
      requiredFields: {
        'dataSchemaVersion',
        'associationId',
        'competitionId',
        'seasonId',
        'gameId',
        'reviewId',
        'revisionId',
        'revisionHash',
        'reviewerAccountId',
        'decision',
        'reasonCode',
        'evidenceRefs',
      },
    ),
    EntitySchemaContract(
      name: 'certificate',
      path:
          'associations/{associationId}/competitions/{competitionId}/seasons/{seasonId}/games/{gameId}/certificates/{certificateId}',
      classification: ContractClassification.canonical,
      mutability: ContractMutability.immutable,
      visibility: ContractVisibility.private,
      requiredFields: {
        'dataSchemaVersion',
        'associationId',
        'competitionId',
        'seasonId',
        'gameId',
        'certificateId',
        'revisionId',
        'revisionHash',
        'certifierAccountId',
        'certificationPolicyVersion',
        'certifiedAt',
      },
      explicitFactFields: {'predecessorCertificateId'},
    ),
    EntitySchemaContract(
      name: 'certificateAction',
      path:
          'associations/{associationId}/competitions/{competitionId}/seasons/{seasonId}/games/{gameId}/certificateActions/{actionId}',
      classification: ContractClassification.canonical,
      mutability: ContractMutability.immutable,
      visibility: ContractVisibility.private,
      requiredFields: {
        'dataSchemaVersion',
        'associationId',
        'competitionId',
        'seasonId',
        'gameId',
        'actionId',
        'certificateId',
        'action',
        'reasonCode',
        'actorAccountId',
        'evidenceRefs',
      },
    ),
    EntitySchemaContract(
      name: 'correction',
      path:
          'associations/{associationId}/competitions/{competitionId}/seasons/{seasonId}/games/{gameId}/corrections/{correctionId}',
      classification: ContractClassification.canonical,
      mutability: ContractMutability.appendOnly,
      visibility: ContractVisibility.private,
      requiredFields: {
        'dataSchemaVersion',
        'associationId',
        'competitionId',
        'seasonId',
        'gameId',
        'correctionId',
        'targetCertificateId',
        'reasonCode',
        'fieldDiff',
        'evidenceRefs',
        'successorWorkspaceId',
      },
    ),
    EntitySchemaContract(
      name: 'projectionBuild',
      path:
          'associations/{associationId}/competitions/{competitionId}/seasons/{seasonId}/projectionBuilds/{buildId}',
      classification: ContractClassification.derived,
      mutability: ContractMutability.buildThenSeal,
      visibility: ContractVisibility.serverPrivate,
      requiredFields: {
        'dataSchemaVersion',
        'associationId',
        'competitionId',
        'seasonId',
        'buildId',
        'state',
        'selectionId',
        'sourceSetHash',
        'expectedCertificateEpoch',
        'expectedPublicationEpoch',
        'expectedPrivacyEpoch',
      },
      explicitFactFields: {'sealedManifestHash'},
    ),
    EntitySchemaContract(
      name: 'publicSelection',
      path:
          'associations/{associationId}/competitions/{competitionId}/seasons/{seasonId}/publicSelections/{selectionId}/games/{gameId}',
      classification: ContractClassification.canonical,
      mutability: ContractMutability.immutable,
      visibility: ContractVisibility.serverPrivate,
      requiredFields: {
        'dataSchemaVersion',
        'associationId',
        'competitionId',
        'seasonId',
        'selectionId',
        'gameId',
        'certificateId',
        'certificateHash',
        'scheduleRevisionId',
      },
    ),
    EntitySchemaContract(
      name: 'aggregateRelease',
      path:
          'associations/{associationId}/competitions/{competitionId}/seasons/{seasonId}/aggregateReleases/{releaseId}/{aggregateKind}/{rowId}',
      classification: ContractClassification.derived,
      mutability: ContractMutability.immutable,
      visibility: ContractVisibility.private,
      requiredFields: {
        'dataSchemaVersion',
        'associationId',
        'competitionId',
        'seasonId',
        'releaseId',
        'projectionVersion',
        'sourceSetHash',
        'payloadHash',
      },
    ),
    EntitySchemaContract(
      name: 'publicationReleaseHead',
      path:
          'associations/{associationId}/competitions/{competitionId}/seasons/{seasonId}/control/current',
      classification: ContractClassification.canonical,
      mutability: ContractMutability.mutableHead,
      visibility: ContractVisibility.serverPrivate,
      requiredFields: {
        'dataSchemaVersion',
        'associationId',
        'competitionId',
        'seasonId',
        'certificateEpoch',
        'publicationEpoch',
        'privacyEpoch',
        'state',
      },
      explicitFactFields: {'activeRelease'},
    ),
    EntitySchemaContract(
      name: 'privacyRelease',
      path: 'associations/{associationId}/playerPublicationPolicies/{playerId}',
      classification: ContractClassification.canonical,
      mutability: ContractMutability.mutableHead,
      visibility: ContractVisibility.serverPrivate,
      requiredFields: {
        'dataSchemaVersion',
        'associationId',
        'playerId',
        'privacyPolicyVersion',
        'privacyEpoch',
        'isMinor',
        'fieldPermissions',
        'authorityEvidenceRefs',
      },
    ),
    EntitySchemaContract(
      name: 'publicProjectionRow',
      path:
          'publicData/{associationId}/competitions/{competitionId}/seasons/{seasonId}/releases/{releaseId}/{projectionKind}/{rowId}',
      classification: ContractClassification.publicProjection,
      mutability: ContractMutability.immutable,
      visibility: ContractVisibility.publicHttpOnly,
      requiredFields: {
        'dataSchemaVersion',
        'associationId',
        'competitionId',
        'seasonId',
        'releaseId',
        'projectionVersion',
        'privacyEpoch',
        'payloadHash',
      },
    ),
  ];

  static EntitySchemaContract named(String name) =>
      entities.singleWhere((entity) => entity.name == name);
}
